import Head from "next/head";
import Header from "./components/header";
import Card from "./components/card";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemons in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <main>
          <div className={styles["main-wrapper"]} data-testid="main-screen">
            <div className={styles["wrapper-outlet"]}>
              <div className="card-container">
                List
                <Card></Card>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
