import Head from "next/head";
import Header from "./components/header";
import Card from "./components/card";
import { FetchBody } from "@/services/interfaces";
import styles from "@/styles/Home.module.css";

import API_PATH from "@/services/constants";
const base = API_PATH;

export const getServerSideProps = async () => {
  const res = await fetch(`${base}`);
  const data = await res.json();
  const pokeList = data.results;

  return {
    props: {
      pokeList,
    },
  };
};

export default function Home({ pokeList }: FetchBody) {
  console.log(pokeList);
  return (
    <>
      <Head>
        <title>Pokemons in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <main>
          <div className={styles["main-wrapper"]} data-testid="main-screen">
            <div className={styles["wrapper-outlet"]}>
              <div className="card-container">
                List
                <Card></Card>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
